### ISSUE TITLE
fallout 4 character planner

### ISSUE THREAD

**Issue by axmaxwell** [mmartinx/mmartinx.github.io#4]
Hey,
I love this page you made, I have been using it and the original for years, but I have a small suggestion.

It needs checkboxes for the seven SPECIAL bobbleheads and an additional checkbox for the perk point you get from the 'You're SPECIAL' book in Sanctuary at the beginning of the game. Otherwise, the 'Level' counter is off and doesn't accurately reflect.

I hope you have time to make this edit, I created a Github acct just to bring this up to you.

Thank you for your time,

axmaxwell

fallout4saga.wordpress.com

**Comment by mmartinx** [comment]
Hi @axmaxwell, thank you for the kind words. I actually had bobbleheads implemented in the original version but for some reason I commented them out. I added them back in, its just a checkbox at the top of the left column that will give you the 7 extra points. I guess I should make that 8 for the you're special.

**Comment by axmaxwell** [comment]
Im sure Im driving you nuts at this point. It all looks good, just the
required level counter increases when you apply the special/book points to
reflect a minimum level of 9.

I really do appreciate the fix though.
